services:
  - type: web
    name: resume-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: karbarkarrr
