services:
  - type: web
    name: resume-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
